let lessons = [
    {
        id: 1001,
        subject: 'Science',
        location: 'London',
        price: 110,
        image: 'images/science.jpg',
        capacity: 5,
    },
    {
        id: 1002,
        subject: 'Animation',
        location: 'London',
        price: 120,
        image: 'images/animation.png',
        capacity: 5,
    },
    {
        id: 1003,
        subject: 'Programing',
        location: 'London',
        price: 105,
        image: 'images/programing.jpg',
        capacity: 5,
    },
    {
        id: 1004,
        subject: 'Maths',
        location: 'London',
        price: 101,
        image: 'images/maths.png',
        capacity: 5,
    },
    {
        id: 1005,
        subject: 'English',
        location: 'London',
        price: 90,
        image: 'images/english.png',
        capacity: 5,
    },
    {
        id: 1006,
        subject: 'French',
        location: 'London',
        price: 150,
        image: 'images/french.png',
        capacity: 5,
    },
    {
        id: 1007,
        subject: 'Business',
        location: 'London',
        price: 110,
        image: 'images/business.png',
        capacity: 5,
    },
    {
        id: 1008,
        subject: 'Histroy',
        location: 'London',
        price: 130,
        image: 'images/history.jpg',
        capacity: 5,    
    },
    {
        id: 1009,
        subject: 'Geography',
        location: 'London',
        price: 100,
        image: 'images/geo.png',
        capacity: 5,    
    },
    {
        id: 1010,
        subject: 'Sports',
        location: 'London',
        price: 100,
        image: 'downloaded.png',
        capacity: 5,    
    }
]